### ISSUE TITLE
Error while importing data Shiny app

### ISSUE THREAD

**Issue by martaint** [yuliangwang/talklr#1]
Hi,

I am trying to use talklr shiny app, however I encounter an error as soon as I upload my test data, which is formatted as shown on the website. 
The error is:
"An error has occurred. Check your logs or contact the app author for clarification."

Any idea what I might do wrong?

Thanks a lot!
Best regards,
Marta

**Comment by yuliangwang** [comment]
Hi Marta,
Thanks for your interest in using talklr. Do you mind showing me a snapshot
of your input data so I can take a look?
Yuliang
----------
Yuliang Wang Ph.D
Research Assistant Professor
Paul G Allen School of Computer Science & Engineering
Institute for Stem Cell and Regenerative Medicine
University of Washington
https://yuliangwang.github.io

**Comment by qtania** [comment]
> Hi,
> 
> I am trying to use talklr shiny app, however I encounter an error as soon as I upload my test data, which is formatted as shown on the website.
> The error is:
> "An error has occurred. Check your logs or contact the app author for clarification."
> 
> Any idea what I might do wrong?
> 
> Thanks a lot!
> Best regards,
> Marta

Hi Marta,

I was facing the same problem. Verify 1) That you are not having the row names printed (if printing from a df or similar to a .csv - also double-check the use of coma or tab), 2) that you have the title for the genes and different cell types as mentioned in the examples, 3)If you are not using Human data (f.e. you are using mus musculus), capitalize the name of the genes. 

Hope this helps ;)

**Comment by martaint** [comment]
Hi, sorry for the very late response!!! I managed to make it work :) thanks a lot for your help!
